### ISSUE TITLE
Copy files to Docker container

### ISSUE THREAD

**Issue by benchengl** [gtDMMB/pmfe#28]
Hello, I am new to it and have problems copying local files from my computer to the Docker container. I used the following command where I believe  `cef79afd8cda` is the Docker container ID.
```
docker cp Downloads/elegans cef79afd8cda:/pmfe
```
But it seems after I ran the command, nothing is copied to the `pmfe` directory. Does anyone know how to fix it?

**Comment by ceheitsch** [comment]
The problem is that``/pmfe`` is not the correct destination path.  In the container, type ``pwd`` to see the correct one.
